<template>
  <div style="height: 90%; overflow-y: auto; overflow-x: hidden">
    <div style="background-color: #d9d9d9">
      <div class="container-fluid p-3">
        <div class="row justify-content-end">
          <div class="col d-flex justify-content-end">
            <button type="button" class="btn filled-btn nowrap btn-wd" @click="nav">
              Search Samples
            </button>
          </div>
        </div>
      </div>
    </div>
    <div style="background-color: white">
      <v-form @submit.prevent="createBatch" id="my-form-data">
      <v-row>
        <div class="container-fluid">
        <fieldset class="border rounded-3 px-5 mx-5 pt-3 user-details-section" style="border-radius: 10px; border: 1px solid #ccc; margin-top: 20px;">
          <!-- <legend class="float-none w-auto px-3 text-xs"> User Details </legend> -->
          <v-form @submit.prevent="createBatch" id="user-details-form">
            <div class="row">
              <div class="col-md-6">
                <div class="row">
                  <div class="text-md font-weight-normal fs-6 mb-2 ml-2">Generated By</div>
                  <div class="col-md-12">
                    <v-select
                      v-model="UserEmail"
                      :items="studyTeam"
                      variant="outlined"
                      density="compact"
                      item-title="name"
                      item-value="name"
                      placeholder="Generated By"
                    >
                      <template v-slot:item="{ props, item }">
                        <v-list-item
                          style="width: 350px;min-height: 40px;padding: 0px 4px"
                          v-bind="props"
                          :disabled="UserEmail != item.raw.name"
                          :title="item.raw.name"
                        ></v-list-item>
                      </template>
                    </v-select>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="row">
                  <label class="text-md font-weight-normal fs-6 mb-2 ml-2">Generated On</label>
                  <div class="col-md-12">
                    <v-text-field
                      density="compact"
                      readOnly
                      type="text"
                      variant="outlined"
                      :value="moment(generatedOn).format('MM-DD-YYYY hh:mm A')"
                      hide-details
                    ></v-text-field>
                  </div>
                </div>
              </div>
            </div>
          </v-form>
        </fieldset>
        </div>
      </v-row>
      <v-row class="align-items-center mb-3" v-if="addButtonStore.sampleStatus === 'DNA_ISOLATION_PASSED'">
        <div class="container-fluid">
          <fieldset class="border rounded-3 px-5 mx-5" style="border-radius: 10px; border: 1px solid #ccc; margin-top: 20px;">
            <legend class="float-none w-auto px-3 text-xs">Kit Details</legend>
            <form @submit.prevent="createBatch" id="kit-details-form">
              <div class="row mb-2">
                <div class="col-md-6">
                  <div class="row">
                    <div class="text-md font-weight-normal fs-6 mb-2 ml-2">Library Kit Name <span class="req">  * </span> </div>
                      <v-select
                        class="custom-select"
                        variant="solo"
                        density="compact"
                        @update:modelValue="handleChangeKit"
                        v-model="kitType"
                        :rules="[(v) => !!v || 'This is required']"
                        required
                        :items="libprepKitTypes"
                        :item-props="itemKitProps"
                      ></v-select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="row">
                    <label class="text-md font-weight-normal fs-6  mb-2 ml-2">Index Plate Name<span class="req">  * </span> </label>
                    <div class="col-md-12 ">
                      <v-select
                        :disabled="!kitType"
                        variant="solo"
                        density="compact"
                        @update:modelValue="handleChangePlate"
                        v-model="indexPlateName"
                        :rules="[(v) => !!v || 'This is required']"
                        required
                        :items="indexPlateNameList"
                        :item-props="itemPlateProps"
                      ></v-select>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="text-md fs-6 mt-0 mb-2 ml-2">Index Plate Sub Types <span class="req">  * </span> </div>
                <div class="col-md-12 mb-3">
                  <v-select
                    variant="solo"
                    :disabled="!kitType || !indexPlateName"
                    density="compact"
                    chips
                    multiple
                    @update:modelValue="handleChangeSubType"
                    v-model="indexPlateSubtypes"
                    :rules="[(v) => (indexPlateSubtypes && indexPlateSubtypes.length > 0 )|| 'This is required']"
                    required
                    :items="indexPlateSubtypesList"
                    :item-props="itemSubTypeProps"
                  ></v-select>
                </div>
              </div>
            </form>
          </fieldset>
        </div>
      </v-row>
      <div v-if="batchStore.searchSampleData.length > 0">
      <v-table class="mt-8">
      <thead>
        <tr class="tr-bg">
          <th>
            <div class="d-flex align-items-center justify-content-start" style="font-weight: 600">
              <input type="checkbox"  @change="handleCheckAll()" v-model="isCheckAll" />
              <div class="pl-2 th-txt">Sample Barcode</div>
            </div>
          </th>
          <th v-for="(header, index) in displayedHeaders" :key="index" scope="col" class="th-txt">
            {{ header }}
          </th>
          <th class="th-txt" v-if="getSampleStatus === 'DNA_ISOLATION_PASSED'">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(item, index) in filteredResults" class="tr-txt" :key="index">
          <td>
            <div class="d-flex align-items-center">
              <div class="pr-2" v-if="viewStore.searchResultsBlock">
                <input type="checkbox"  v-model="item.isSelected" @change="handleCheck(item)" />
              </div>
              <div>{{ item.sampleBarcode ? item.sampleBarcode : item.sample_barcode ? item.sample_barcode:'-' }}</div>
            </div>
          </td>
           <SearchSamplesTable :item="item"/>
          <td v-if="getSampleStatus === 'DNA_ISOLATION_PASSED'"><v-icon
              v-if="item.isOriginal === undefined" class="add-icon" @click="addDuplicateRow(index)" icon="mdi mdi-plus-circle"></v-icon>
            <v-icon icon="mdi mdi-minus-circle" class="delete-icon" v-else @click="removeRow(index)"></v-icon>
          </td>
        </tr>
      </tbody>
    </v-table>
    </div>
  </v-form>
      <div v-if="batchStore.searchSampleData.length > 0"
        class="d-flex justify-content-center align-items-center br-bt fixed"
      >
        <button type="button" class="btn border-btn m-2" @click="handleClose">close</button>
        <button type="submit" form="my-form-data" class="btn filled-btn">Save</button>
      </div>
    </div>
  </div>
  <EsignatureModal
    v-if="viewStore.eSignatureModal"
    :handleSubmit="handleSubmit"
    :text="EsignatureText()"
  />
  <GeneratePoolView
    v-if="getSampleStatus === 'LIB_PREP_DAY1_PASSED'"
    :showModal="showPoolModal"
    :selectedSamples="finalSelectionSamples"
    :close="closePoolModal"
    :generatedBy="generatedBy"
  >
  </GeneratePoolView>
  <v-snackbar :timeout="2000" location="top" v-model="showAlert" color="#dc3545">
      {{ alertMessage }}
      <template v-slot:actions>
        <v-icon @click="showAlert = false" icon="mdi mdi-close-circle-outline" />
      </template>
    </v-snackbar>
</template>
<script setup>
import { useRouter } from 'vue-router';
import { useBatchListStore } from '../../stores/batchListStore';
import { ref, watch, onMounted ,computed} from 'vue';
import { SampleController } from '../../Controllers/sampleController';
import { useStudyStore } from '../../stores/studyStore';
import EsignatureModal from '../../components/EsignatureModal.vue';
import { useViewStore } from '../../stores/viewStore';
import { useKitStore } from '../../stores/kitStore';
import GeneratePoolView from '../LibraryPreparation/GeneratePoolView.vue';
import { useAddButtonStore } from '../../stores/addButtonStore';
import moment from 'moment';
import SearchSamplesTable from './SearchSamplesTable.vue';
import { searchGridHeaders } from '../../Constants/searchGridHeaders';
const batchStore = useBatchListStore()
const router = useRouter()
const studyStore = useStudyStore()
const studyTeam = ref([])
const viewStore = useViewStore()
const generatedBy = ref('')
const kitStore = useKitStore();
const UserEmail = localStorage.getItem('userName')
const generatedOn = ref(new Date())
const getSampleStatus = localStorage.getItem('sampleStatus')
const showPoolModal = ref(false)
const addButtonStore = useAddButtonStore()
const kitType = ref(kitStore.getKitName);
const indexPlateName = ref( kitStore.getPlateName  === '' ? '': JSON.parse(kitStore.getPlateName));
const indexPlateSubtypes = ref( kitStore.getPlateSubTypes === null ? null : JSON.parse(kitStore.getPlateSubTypes));
const libKitList = ref([])
const libprepKitTypes = ref([])
const indexPlateSubtypesList = ref([])
const indexPlateNameList = ref([])
const errorMsg = ref('')
const subTypeFilterData = ref([])
const isCheckAll=ref(true);
const showAlert = ref(false);
const alertMessage = ref("");
const displayedHeaders = computed(() => {
  return searchGridHeaders().allHeaders[getSampleStatus] || [];
});
const finalSelectionSamples=ref()
const handleCheckAll=()=>{
  batchStore.searchSampleData.forEach((item) => (item.isSelected = isCheckAll.value));
  
}
const handleCheck=()=>{
  const allSwitchStatesTrue = batchStore.searchSampleData.every((item) => item.isSelected);
  if (allSwitchStatesTrue) {
    isCheckAll.value = true
  }
  else {
   isCheckAll.value = false
  }
}
onMounted(()=> {
  if(getSampleStatus !== 'DNA_ISOLATION_PASSED') {
    kitStore.resetStore();
  }
  const plateNameList = kitStore.getPlateNameList;
  const plateSubTypeList = kitStore.getPlateSubTypesList;
  if(plateNameList && plateNameList.length > 0) {
    indexPlateNameList.value = plateNameList;
  }
  if(plateSubTypeList && plateSubTypeList.length > 0) {
    indexPlateSubtypesList.value = plateSubTypeList;
  }
})
const EsignatureText = () => {
  switch (getSampleStatus) {
    case 'Accessioned':
      return 'I am creating DNA isolation batch'
    case 'DNA_ISOLATION_PASSED':
      return 'I am creating LIB_PREP_DAY1 batch'
    case 'LIB_PREP_DAY2_PASSED':
      return 'I am creating NGS run'
    default:
      return ''
  }
}
const handleChangeKit = (e) => {
  indexPlateName.value = '';
  indexPlateSubtypes.value = null;
  libKitList?.value?.map((value) => {
    if (e === value.library_preparation_kit_name) {
      indexPlateNameList.value = value?.index_plate_names?.map((plate) => {
        return {
          label: plate.index_plate_name,
          name: plate.index_plate_name,
        };
      });
    }
    kitStore.setPlateNameList(indexPlateNameList.value);
  });
  kitStore.setKitName(e);
};

const filteredResults = computed(() =>
     batchStore.searchSampleData
)
const addDuplicateRow = (index) => {
  const originalItem = batchStore.searchSampleData[index];
  const newItem = { ...originalItem, isOriginal: false };
  const newResults = [...batchStore.searchSampleData];
  newResults.splice(index + 1, 0, newItem);
  batchStore.searchSampleData = newResults;
};



const removeRow = (index) => {
  filteredResults.value.splice(index, 1);
};
const handleChangeSubType = (e) => {
  indexPlateSubtypes.value = e.filter((index) => index !== '');
  kitStore.setPlateSubTypes(JSON.stringify(e));
};

const handleChangePlate = (e) => { 
  indexPlateSubtypes.value = null;
  libKitList?.value?.map((value) => {
    value?.index_plate_names?.map((plate) => {
      if (e.name === plate.index_plate_name) {
        indexPlateSubtypesList.value = plate?.index_plate_subtypes?.map((subtype) => {
          return {
            label: subtype,
            name: subtype,
          };
        });
      }
    });
    kitStore.setPlateSubTypesList(indexPlateSubtypesList.value);
  });
  kitStore.setPlateName(JSON.stringify(e));
};

const fetchStudyTeam = async () => {
  const inputModel = {
    studyTeamModel: {
      studyId: studyStore.selectedStudy,
      accountStatus: [0, 1]
    }
  }
  const results = await SampleController.getStudyTeams(inputModel)
  if (results?.data?.length > 0) {
    studyTeam.value = results?.data?.map((value) => {
      return {
        name: value.email,
      }
    })
  }
}
const closePoolModal = () => {
  showPoolModal.value = false
}
const getKitTypes = async () => {
  const response = await SampleController.getAllKitTypes()
  if (response?.data?.length > 0) {
    libKitList.value = response.data
    libprepKitTypes.value = response?.data?.map((value) => {
      return {
        label: value.library_preparation_kit_name,
        value: value.library_preparation_kit_name
      }
    })
  }
}
watch(
  () => studyStore.selectedStudy,
  (newStudy) => {
    fetchStudyTeam()
    getKitTypes()
  },
  { immediate: true }
)
const nav = () => {
  router.push('/searchSample')
  viewStore.getSearchResultsBlock(false);
  const filterData = batchStore.searchSampleData.filter(item => item.isSelected === true);
  batchStore.resetSelected(filterData)
}

const handleClose = () => {
  kitStore.resetStore();
  if(getSampleStatus == 'Accessioned') {
    router.push('/batchList')
  } else if(getSampleStatus == 'DNA_ISOLATION_PASSED') {
    router.push('/libbatchlist')
  } else if(getSampleStatus == 'LIB_PREP_DAY1_PASSED') {
    router.push('/libbatchlist')
    localStorage.setItem('lipTab','day2')
  }
  else {
    router.push('/NGSRuns')
  }
  viewStore.getSearchResultsBlock(false)
  batchStore.getSaveSelection([], false, true)
}

const itemKitProps = (item) => {
  return {
    title: item.label
  }
}
const itemPlateProps = (item) => {
  return {
    title: item.label
  }
}
const itemSubTypeProps = (item) => {
  return {
    title: item.label
  }
}

const handleSubmit = async () => {
  let caseSamples = [];
  if (batchStore.searchSampleData && batchStore.searchSampleData.length > 0) {
  batchStore.searchSampleData.forEach((item) => {
    if (item.isSelected) { 
      if(getSampleStatus === 'Accessioned'){
        caseSamples.push({ caseSampleId: item.caseSampleId, poolNo: 0 });
      }
      else {
        caseSamples.push({ caseSampleId: Number(item.entity_id), poolNo: 0,batchEntityId:item.batch_entity_id});
      }
    }
  });
}
  const batchAttribute = [
    {
      attributeName: 'generated_by',
      attributeValue: UserEmail
    },
    {
      attributeName: 'generated_on',
      attributeValue: new Date()
    }
  ]
  if (getSampleStatus === 'DNA_ISOLATION_PASSED') {
    batchAttribute.push(
      {
        attributeName: 'library_preparation_kit_name',
        attributeValue: kitType.value
      },
      {
        attributeName: 'index_plate_name',
        attributeValue: indexPlateName.value.name
      },
      {
        attributeName: 'index_plate_subtype',
        attributeValue: subTypeFilterData.value.join(',')
      }
    )
  }
  const inputModel = {
    batchModel: {
      batch: {
        batchId: null,
        batchName: null,
        batchNumber: null,
        batchType:
          getSampleStatus === 'Accessioned'
            ? 'DNA_ISOLATION'
            : getSampleStatus === 'DNA_ISOLATION_PASSED'
            ? 'LIB_PREP_DAY1'
            : getSampleStatus === 'LIB_PREP_DAY1_PASSED'
            ? 'LIB_PREP_DAY2'
            : getSampleStatus === 'LIB_PREP_DAY2_PASSED' && 'NGS',
        batchStatus: 'PENDING',
        batchAttribute: batchAttribute,
        caseSamples: caseSamples
      },
      isLibraryIdGeneration: getSampleStatus === 'DNA_ISOLATION_PASSED' ? true : false,
      isLPoolIdGeneration: getSampleStatus === 'LIB_PREP_DAY1_PASSED' ? true : false
    },
    eSignatureModel: {
      username: viewStore.eSignatureForm.username,
      password: viewStore.eSignatureForm.password,
      changeReasonDetail: viewStore.eSignatureForm.changeReasonDetail
    }
  }
  const navTo =
    getSampleStatus === 'Accessioned'
      ? '/batchList'
      : getSampleStatus === 'DNA_ISOLATION_PASSED'
      ? '/libbatchlist'
      : getSampleStatus === 'LIB_PREP_DAY2_PASSED' && '/NGSRuns';
    await SampleController.createBatch(inputModel, router, navTo)
}

const createBatch = (fields) => {
  generatedBy.value = fields.genrated_by
  const allSelectedFalse = batchStore.searchSampleData.every(item => !item.isSelected);
  if(allSelectedFalse){
    showAlert.value = true
    alertMessage.value = 'Please select atleast one sample';
  }
  else{
  if (getSampleStatus === 'DNA_ISOLATION_PASSED') {
    subTypeFilterData.value = indexPlateSubtypes?.value?.length > 0 ? indexPlateSubtypes?.value?.filter((item) => item !== '') : [];
    subTypeFilterData.value = subTypeFilterData.value.map((item)=> `${item.label}`);
    if (subTypeFilterData.value.length === 0) {
      errorMsg.value = 'IndexPlateSubtypes is required'
    } else {
      viewStore.getEsignatureModal(true)
    }
  } else if (getSampleStatus === 'LIB_PREP_DAY1_PASSED') {
    showPoolModal.value = true;
    finalSelectionSamples.value = batchStore.searchSampleData.filter(item => item.isSelected === true);
  } else {
    viewStore.getEsignatureModal(true)
  }
}
}

</script>
<style scoped>
.req {
  color: #ea0000;
}
.nowrap {
  white-space: nowrap;
}

.fixed {
  position: fixed;
  bottom: 27px;
  width: 100%;
}
.errormsg {
  margin-top: -21px;
  font-size: 12px;
  color: #ea0000;
}
.wordwrap {
  word-wrap: break-word !important;
  white-space: wrap;
}
.add-icon {
  height: 30px;
  width: 30px;
  color: #007BFF;
}

.delete-icon {
  height: 30px;
  width: 30px;
  color: red;
}
</style>
