<template>
    <div style="height: 90%; overflow-y: auto; overflow-x: hidden">
      <div style="background-color: #d9d9d9">
        <div class="container-fluid p-3">
          <div class="row justify-content-end">
            <div class="col d-flex justify-content-end">
              <button type="button" class="btn filled-btn nowrap btn-wd" @click="nav">
                Search Samples
              </button>
            </div>
          </div>
        </div>
      </div>
      <div style="background-color: white">
        <div class="p-5">
          <FormKit
            type="form"
            :incomplete-message="false"
            :actions="false"
            id="my-form-data"
          >
            <v-row justify="space-around">
              <v-col cols="12" md="4" sm="12" xs="12">
                <div class="d-flex align-items-center">
                  <span class="batchNo label-clr">Generated By&nbsp;</span>
                  <div style="width: 100%">
                    <FormKit
                      style="
                        width: 100%;
                        background: white !important;
                        border: 1px solid #a9a9a9;
                        font-size: 16px !important;
                      "
                      type="select"
                      name="genrated_by"
                      v-model="UserEmail"
                      placeholder="Generated By"
                      :options="studyTeam"
                      validation="required"
                    />
                  </div>
                </div>
              </v-col>
              <v-col cols="12" md="4" sm="12" xs="12">
                <div class="d-flex align-items-center">
                  <span class="batchNo label-clr">Generated On&nbsp;</span>
                  <v-text-field density="compact" readOnly variant="outlined" v-model="generatedOn" hide-details></v-text-field>
                </div>
              </v-col>
            </v-row>
          </FormKit>
        </div>
      </div>
    </div>
   </template>
  <script setup>
  import { useRouter } from 'vue-router'
  import { ref, watch } from 'vue'
  import { formatDate } from '../Utils/helperFunctions';
import { SampleController } from '../Controllers/sampleController';
import { useStudyStore } from '../stores/studyStore';
const studyTeam = ref([]);
const studyStore = useStudyStore();
const router = useRouter();
const props = defineProps({
  path: String
})
  const UserEmail = localStorage.getItem("userName");
  const generatedOn =  ref(formatDate((new Date().getTime())));
  const fetchStudyTeam = async () => {
  const inputModel = {
    studyTeamModel: {
      studyId: studyStore.selectedStudy,
      accountStatus: [0, 1]
    }
  }
  const results = await SampleController.getStudyTeams(inputModel)
  if (results.data.length > 0) {
    studyTeam.value = results.data.map((value) => {
      const isEmailMatch = value.email === localStorage.getItem('userName')
      return {
        label: `${value.name} ${value.lname} (${value.email})`,
        value: value.email,
        attrs: { disabled: !isEmailMatch }
      }
    })
  }
}
const nav = (path) => {
  router.push(props.path);
  //viewStore.getSearchResultsBlock(false);
  //batchStore.getisCheckAll(false);
}
watch(
  () => studyStore.selectedStudy,
  (newStudy) => {
    fetchStudyTeam()
  },
  { immediate: true }
)
  </script>
  <style scoped>
  .page-ht {
    height: 100%;
    overflow-y: auto;
  }
  
  .batchNo {
    color: #eb4c6e;
    font-weight: 500;
    font-size: 18px;
    white-space: nowrap;
  }
  
  .box-shadow {
    box-shadow: 2px 2px 6px 0px #a9a9a933;
  }
  
  .label-clr {
    color: #000000;
    font-size: 16px !important;
  }
  
  .nowrap {
    white-space: nowrap;
  }
  
  .fixed {
    position: fixed;
    bottom: 27px;
    width: 100%;
  }
  </style>
  